### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by dustyeric** [dustyeric/CalculatorTest#1]
There is an issue

**Comment by dustyeric** [comment]
i close the isssue

**Comment by supersun** [comment]
ok

**Comment by jintell** [comment]
Ok

[cid:image001.png@01D03BDF.4E163B50]
[cid:image002.png@01CE35F1.DA3B8F90]http://www.facebook.com/cwlgroup[cid:image003.png@01CE35F1.DA3B8F90]http://www.linkedin.com/company/computer-warehouse-group-plc/[cid:image004.jpg@01CE35F1.DA3B8F90]http://www.twitter.com/CWGAfrica
